<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Accounting\ChartOfAccount;
use App\Models\Tenant;

class DefaultChartOfAccountsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get all active tenants
        $tenants = Tenant::where('status', 'active')->get();

        $defaultAccounts = [
            // ASSETS (1000-1999)
            [
                'account_code' => '1000',
                'account_name' => 'ASSETS',
                'account_type' => 'asset',
                'normal_balance' => 'debit',
                'description' => 'All assets',
                'is_active' => true,
                'is_system' => true,
                'allow_manual_entry' => false,
                'level' => 1,
            ],
            
            // Current Assets (1100-1499)
            [
                'account_code' => '1100',
                'account_name' => 'Current Assets',
                'account_type' => 'asset',
                'normal_balance' => 'debit',
                'description' => 'Assets expected to be converted to cash within one year',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => false,
                'level' => 2,
            ],
            [
                'account_code' => '1110',
                'account_name' => 'Cash in Hand',
                'account_type' => 'asset',
                'normal_balance' => 'debit',
                'description' => 'Physical cash, petty cash',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'is_cash_account' => true,
                'level' => 3,
            ],
            [
                'account_code' => '1120',
                'account_name' => 'Cash at Bank',
                'account_type' => 'asset',
                'normal_balance' => 'debit',
                'description' => 'Bank accounts, checking accounts',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'is_bank_account' => true,
                'level' => 3,
            ],
            [
                'account_code' => '1130',
                'account_name' => 'Accounts Receivable',
                'account_type' => 'asset',
                'normal_balance' => 'debit',
                'description' => 'Money owed by customers',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'level' => 3,
            ],
            [
                'account_code' => '1140',
                'account_name' => 'Loan Receivables',
                'account_type' => 'asset',
                'normal_balance' => 'debit',
                'description' => 'Loans disbursed to clients',
                'is_active' => true,
                'is_system' => true,
                'allow_manual_entry' => false,
                'level' => 3,
            ],
            [
                'account_code' => '1150',
                'account_name' => 'Interest Receivable',
                'account_type' => 'asset',
                'normal_balance' => 'debit',
                'description' => 'Accrued interest on loans',
                'is_active' => true,
                'is_system' => true,
                'allow_manual_entry' => false,
                'level' => 3,
            ],
            [
                'account_code' => '1160',
                'account_name' => 'Inventory',
                'account_type' => 'asset',
                'normal_balance' => 'debit',
                'description' => 'Stock, goods for sale',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'level' => 3,
            ],
            [
                'account_code' => '1170',
                'account_name' => 'Prepaid Expenses',
                'account_type' => 'asset',
                'normal_balance' => 'debit',
                'description' => 'Prepaid rent, insurance, subscriptions',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'level' => 3,
            ],
            
            // Fixed Assets (1500-1999)
            [
                'account_code' => '1500',
                'account_name' => 'Fixed Assets',
                'account_type' => 'asset',
                'normal_balance' => 'debit',
                'description' => 'Long-term tangible assets',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => false,
                'level' => 2,
            ],
            [
                'account_code' => '1510',
                'account_name' => 'Property & Equipment',
                'account_type' => 'asset',
                'normal_balance' => 'debit',
                'description' => 'Buildings, land, equipment',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'level' => 3,
            ],
            [
                'account_code' => '1520',
                'account_name' => 'Furniture & Fixtures',
                'account_type' => 'asset',
                'normal_balance' => 'debit',
                'description' => 'Office furniture, fixtures',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'level' => 3,
            ],
            [
                'account_code' => '1530',
                'account_name' => 'Computer Equipment',
                'account_type' => 'asset',
                'normal_balance' => 'debit',
                'description' => 'Computers, laptops, servers',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'level' => 3,
            ],
            [
                'account_code' => '1540',
                'account_name' => 'Vehicles',
                'account_type' => 'asset',
                'normal_balance' => 'debit',
                'description' => 'Cars, motorcycles, trucks',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'level' => 3,
            ],
            [
                'account_code' => '1590',
                'account_name' => 'Accumulated Depreciation',
                'account_type' => 'asset',
                'normal_balance' => 'credit',
                'description' => 'Contra-asset account for depreciation',
                'is_active' => true,
                'is_system' => true,
                'allow_manual_entry' => false,
                'level' => 3,
            ],
            
            // LIABILITIES (2000-2999)
            [
                'account_code' => '2000',
                'account_name' => 'LIABILITIES',
                'account_type' => 'liability',
                'normal_balance' => 'credit',
                'description' => 'All liabilities',
                'is_active' => true,
                'is_system' => true,
                'allow_manual_entry' => false,
                'level' => 1,
            ],
            
            // Current Liabilities (2100-2499)
            [
                'account_code' => '2100',
                'account_name' => 'Current Liabilities',
                'account_type' => 'liability',
                'normal_balance' => 'credit',
                'description' => 'Liabilities due within one year',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => false,
                'level' => 2,
            ],
            [
                'account_code' => '2110',
                'account_name' => 'Accounts Payable',
                'account_type' => 'liability',
                'normal_balance' => 'credit',
                'description' => 'Money owed to suppliers',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'level' => 3,
            ],
            [
                'account_code' => '2120',
                'account_name' => 'Client Deposits',
                'account_type' => 'liability',
                'normal_balance' => 'credit',
                'description' => 'Savings and deposits from clients',
                'is_active' => true,
                'is_system' => true,
                'allow_manual_entry' => false,
                'level' => 3,
            ],
            [
                'account_code' => '2130',
                'account_name' => 'Accrued Expenses',
                'account_type' => 'liability',
                'normal_balance' => 'credit',
                'description' => 'Expenses incurred but not yet paid',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'level' => 3,
            ],
            [
                'account_code' => '2140',
                'account_name' => 'Taxes Payable',
                'account_type' => 'liability',
                'normal_balance' => 'credit',
                'description' => 'Taxes owed to government',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'level' => 3,
            ],
            [
                'account_code' => '2150',
                'account_name' => 'Short-term Loans',
                'account_type' => 'liability',
                'normal_balance' => 'credit',
                'description' => 'Loans payable within one year',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'level' => 3,
            ],
            
            // Long-term Liabilities (2500-2999)
            [
                'account_code' => '2500',
                'account_name' => 'Long-term Liabilities',
                'account_type' => 'liability',
                'normal_balance' => 'credit',
                'description' => 'Liabilities due after one year',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => false,
                'level' => 2,
            ],
            [
                'account_code' => '2510',
                'account_name' => 'Long-term Loans',
                'account_type' => 'liability',
                'normal_balance' => 'credit',
                'description' => 'Loans payable after one year',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'level' => 3,
            ],
            
            // EQUITY (3000-3999)
            [
                'account_code' => '3000',
                'account_name' => 'EQUITY',
                'account_type' => 'equity',
                'normal_balance' => 'credit',
                'description' => 'Owner\'s equity',
                'is_active' => true,
                'is_system' => true,
                'allow_manual_entry' => false,
                'level' => 1,
            ],
            [
                'account_code' => '3100',
                'account_name' => 'Share Capital',
                'account_type' => 'equity',
                'normal_balance' => 'credit',
                'description' => 'Capital contributed by owners',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'level' => 2,
            ],
            [
                'account_code' => '3200',
                'account_name' => 'Retained Earnings',
                'account_type' => 'equity',
                'normal_balance' => 'credit',
                'description' => 'Accumulated profits',
                'is_active' => true,
                'is_system' => true,
                'allow_manual_entry' => false,
                'level' => 2,
            ],
            [
                'account_code' => '3300',
                'account_name' => 'Current Year Earnings',
                'account_type' => 'equity',
                'normal_balance' => 'credit',
                'description' => 'Net income for current year',
                'is_active' => true,
                'is_system' => true,
                'allow_manual_entry' => false,
                'level' => 2,
            ],
            
            // INCOME (4000-4999)
            [
                'account_code' => '4000',
                'account_name' => 'INCOME',
                'account_type' => 'income',
                'normal_balance' => 'credit',
                'description' => 'All revenue and income',
                'is_active' => true,
                'is_system' => true,
                'allow_manual_entry' => false,
                'level' => 1,
            ],
            [
                'account_code' => '4100',
                'account_name' => 'Interest Income',
                'account_type' => 'income',
                'normal_balance' => 'credit',
                'description' => 'Interest earned from loans',
                'is_active' => true,
                'is_system' => true,
                'allow_manual_entry' => false,
                'level' => 2,
            ],
            [
                'account_code' => '4200',
                'account_name' => 'Fee Income',
                'account_type' => 'income',
                'normal_balance' => 'credit',
                'description' => 'Processing fees, service charges',
                'is_active' => true,
                'is_system' => true,
                'allow_manual_entry' => false,
                'level' => 2,
            ],
            [
                'account_code' => '4300',
                'account_name' => 'Penalty Income',
                'account_type' => 'income',
                'normal_balance' => 'credit',
                'description' => 'Late payment penalties',
                'is_active' => true,
                'is_system' => true,
                'allow_manual_entry' => false,
                'level' => 2,
            ],
            [
                'account_code' => '4400',
                'account_name' => 'Other Income',
                'account_type' => 'income',
                'normal_balance' => 'credit',
                'description' => 'Miscellaneous income',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'level' => 2,
            ],
            
            // EXPENSES (5000-5999)
            [
                'account_code' => '5000',
                'account_name' => 'EXPENSES',
                'account_type' => 'expense',
                'normal_balance' => 'debit',
                'description' => 'All expenses',
                'is_active' => true,
                'is_system' => true,
                'allow_manual_entry' => false,
                'level' => 1,
            ],
            
            // Operating Expenses (5100-5499)
            [
                'account_code' => '5100',
                'account_name' => 'Operating Expenses',
                'account_type' => 'expense',
                'normal_balance' => 'debit',
                'description' => 'Day-to-day operating costs',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => false,
                'level' => 2,
            ],
            [
                'account_code' => '5110',
                'account_name' => 'Salaries & Wages',
                'account_type' => 'expense',
                'normal_balance' => 'debit',
                'description' => 'Employee salaries and wages',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'level' => 3,
            ],
            [
                'account_code' => '5120',
                'account_name' => 'Rent Expense',
                'account_type' => 'expense',
                'normal_balance' => 'debit',
                'description' => 'Office rent',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'level' => 3,
            ],
            [
                'account_code' => '5130',
                'account_name' => 'Utilities',
                'account_type' => 'expense',
                'normal_balance' => 'debit',
                'description' => 'Electricity, water, internet',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'level' => 3,
            ],
            [
                'account_code' => '5140',
                'account_name' => 'Office Supplies',
                'account_type' => 'expense',
                'normal_balance' => 'debit',
                'description' => 'Stationery, supplies',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'level' => 3,
            ],
            [
                'account_code' => '5150',
                'account_name' => 'Depreciation Expense',
                'account_type' => 'expense',
                'normal_balance' => 'debit',
                'description' => 'Depreciation of fixed assets',
                'is_active' => true,
                'is_system' => true,
                'allow_manual_entry' => false,
                'level' => 3,
            ],
            [
                'account_code' => '5160',
                'account_name' => 'Insurance Expense',
                'account_type' => 'expense',
                'normal_balance' => 'debit',
                'description' => 'Insurance premiums',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'level' => 3,
            ],
            [
                'account_code' => '5170',
                'account_name' => 'Marketing & Advertising',
                'account_type' => 'expense',
                'normal_balance' => 'debit',
                'description' => 'Marketing and advertising costs',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'level' => 3,
            ],
            [
                'account_code' => '5180',
                'account_name' => 'Professional Fees',
                'account_type' => 'expense',
                'normal_balance' => 'debit',
                'description' => 'Legal, accounting, consulting fees',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'level' => 3,
            ],
            [
                'account_code' => '5190',
                'account_name' => 'Bank Charges',
                'account_type' => 'expense',
                'normal_balance' => 'debit',
                'description' => 'Bank fees and charges',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'level' => 3,
            ],
            
            // Loan Loss Provision (5500-5599)
            [
                'account_code' => '5500',
                'account_name' => 'Loan Loss Provision',
                'account_type' => 'expense',
                'normal_balance' => 'debit',
                'description' => 'Provision for bad debts',
                'is_active' => true,
                'is_system' => true,
                'allow_manual_entry' => false,
                'level' => 2,
            ],
            [
                'account_code' => '5600',
                'account_name' => 'Other Expenses',
                'account_type' => 'expense',
                'normal_balance' => 'debit',
                'description' => 'Miscellaneous expenses',
                'is_active' => true,
                'is_system' => false,
                'allow_manual_entry' => true,
                'level' => 2,
            ],
        ];

        foreach ($tenants as $tenant) {
            foreach ($defaultAccounts as $account) {
                // Check if account already exists for this tenant
                $exists = ChartOfAccount::where('tenant_id', $tenant->id)
                    ->where('account_code', $account['account_code'])
                    ->exists();

                if (!$exists) {
                    $accountData = array_merge($account, [
                        'tenant_id' => $tenant->id,
                        'opening_balance' => 0,
                        'current_balance' => 0,
                        'currency' => 'TZS',
                    ]);
                    
                    // Remove category_id if it exists since it's optional
                    unset($accountData['category_id']);
                    
                    ChartOfAccount::create($accountData);
                }
            }
        }

        $this->command->info('Default Chart of Accounts created for all active tenants.');
    }
}
